apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: coderev

labels:
  - pairs:
      app.kubernetes.io/name: coderev
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false

resources:
  - namespace.yaml
  - configmap.yaml
  - api/deployment.yaml
  - api/service.yaml
  - api/hpa.yaml
  - worker/deployment.yaml
  - worker/pdb.yaml
